### PR TITLE
When authenticating also return the identity URL 

### PR DESCRIPTION
**Pull request by dcolens**
as it is sometimes easier to get the URL directly instead of the orgId and userId

### CODE REVIEW

**Comment by dcolens** [comment]
Any chance to get this patch in, identity URL is very useful!

**Comment by stomita** [comment]
@dcolens I understand it is valuable. Please just wait for official merge.

**Comment by stomita** [comment]
Implemented on 0.6.2

**Comment by dcolens** [comment]
Thanks

Did

**Pull request closed without merging**
